# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      #fail-fast: false
      matrix:
        python_version: [3.8, 3.9]
        # 2021-11: only dev supports 3.10
        sphinx_version: [2.*, 3.*]
        include:
          # sphinx 1.8
          - python_version: "2.7"
            sphinx_version: "1.8"
          - python_version: "3.5"
            sphinx_version: "1.8"
          # sphinx 3.1
          - python_version: "3.8"
            sphinx_version: "3.1"
          # sphinx 4.1
          - python_version: "3.9"
            sphinx_version: "4.1"
          # sphinx dev
          - python_version: "3.10"
            sphinx_version: "dev"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies (sphinx==${{ matrix.sphinx_version }})
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt flake8
        if [ ${{ matrix.sphinx_version }} = dev ] ; then
            pip install https://github.com/sphinx-doc/sphinx/archive/master.zip
        else
            pip install sphinx==${{ matrix.sphinx_version }}
        fi
    - name: pip list
      run: |
        pip list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest .
